// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jeigrthjmzruagaydfib.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImplaWdydGhqbXpydWFnYXlkZmliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg3NzcwNTIsImV4cCI6MjA1NDM1MzA1Mn0.-JRtLPAIAfn6eeDapJeXJUL7Os5Z_8VB0TjzaFMEppQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);